### ISSUE TITLE
Insert remote host name adds number if multiple windows to same host open

### ISSUE THREAD

**Issue by t-jones** [duncs/clusterssh#34]
As the title says, if you send the remote host name to two xterms open to the same host, one receives a '1' suffixed to the host name.

**Comment by duncs** [comment]
Correct, this is expected behaviour. 

There are two macros, one contains the "real" host name used to connect, the other the name used as the window title. This is so if you do connect twice to the same machine and copy a file using the macro you can use the appropriate one to make sure the files don't overwrite each other

Duncs
