### ISSUE TITLE
Config File(s) Not Accepted

### ISSUE THREAD

**Issue by stone212** [duncs/clusterssh#83]
I have the following line in my .csshrc:

`VPNs = vpn1 vpn2 vpn3 vpn4`

... where vpnX is associated with an IP in /etc/hosts and where I can successfully do "ssh vpnX"

When I run "cssh" from the command line, I get the following error:

> Unknown configuration parameters: vpns

This is the same error I get when I put that line in .clusterssh/config

(Side note: what the hell is .clusterssh/config?)

**Comment by duncs** [comment]
What version are you using?  The current version is 4.10

`$HOME/.csshrc` was migrated to `$HOME/.clusterssh/config` a long time ago - "recent" versions of `clusterssh` will move the config for you into the new location.  This is because I found I needed more config options than the `.csshrc` could give me in one file.

You can add the `vpns = vpn1 vpn2 vpn3` into `$HOME/.clusterssh/clusters` (originally you would have to add in `vpns` into the `clusters = ...` configuration option in `.csshrc` as well as defining what `vpns` was)

  Duncs
